# Generated by Django 4.0.5 on 2022-06-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_unisex_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unisex',
            name='main_photo',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
