# Generated by Django 4.0.5 on 2022-06-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_newarrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(help_text='최대 30글자', max_length=30)),
                ('comment', models.CharField(help_text='최대 300글자', max_length=300)),
            ],
        ),
    ]
