# Generated by Django 4.0.5 on 2022-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_commentformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentformmodel',
            name='recomment_content',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commentformmodel',
            name='recomment_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
