# Generated by Django 4.0.5 on 2022-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_commentformmodel_recomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentformmodel',
            name='recomment_content',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='commentformmodel',
            name='recomment_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
