# Generated by Django 4.0.5 on 2022-06-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_postdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='PostDetailContent',
            new_name='content',
        ),
    ]
