# Generated by Django 4.0.5 on 2022-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_unisex_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_slide_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_slide', models.ImageField(upload_to='first_slide/')),
                ('second_slide', models.ImageField(upload_to='second_slide/')),
                ('third_slide', models.ImageField(upload_to='third_slide/')),
            ],
        ),
        migrations.CreateModel(
            name='weekly_best_slide_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_slide', models.ImageField(upload_to='first_slide/')),
                ('second_slide', models.ImageField(upload_to='second_slide/')),
                ('third_slide', models.ImageField(upload_to='third_slide/')),
            ],
        ),
    ]
