# Generated by Django 4.0.5 on 2022-07-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
